"""Menu photos -> a training pack for one specific restaurant.

Two steps, both on Claude Sonnet 5.5:
1. extract(): the photos -> the menu as printed (dishes, wines, drinks). Nothing
   is added that is not on the photo; the app shows it for review.
2. start_build(): the reviewed menu -> a pack in the same schema as the built-in
   content (cards, speak phrases, quiz, scenes), generated by several calls in
   parallel. It runs in a background thread; the app polls GET /packs/<id>.

One restaurant costs ~$0.25-0.40. Guards: an access code (MENU_CODE env) and a
daily cap (MENU_DAILY_USD, default 3). Spend goes to /data/spend.jsonl with
kind "menu". Packs live in /data/packs/<id>.json and are public by their
unguessable id (they hold only a menu, no personal data).
"""
import json
import os
import re
import secrets
import threading
from concurrent.futures import ThreadPoolExecutor
from datetime import date, datetime, timezone

import checker  # shared client, key handling and spend log

MODEL = os.environ.get("MENU_MODEL", "claude-sonnet-5-5")
DAILY_USD = float(os.environ.get("MENU_DAILY_USD", "3"))
CODE = os.environ.get("MENU_CODE", "")
PACKS = os.path.join(checker.DATA, "packs")
CHUNK = 12          # dishes per generation call
_lock = threading.Lock()


class AccessDenied(Exception):
    pass


def _check_access(code):
    if not CODE or not secrets.compare_digest(str(code or ""), CODE):
        raise AccessDenied()
    today = date.today().isoformat()
    spent = sum(r.get("usd", 0) for r in checker._read_spend() if r.get("day") == today and r.get("kind") == "menu")
    if spent >= DAILY_USD:
        raise OverflowError("daily menu budget reached")


def _log(usage_rows):
    with _lock, open(checker.SPEND_FILE, "a", encoding="utf-8") as f:
        for u in usage_rows:
            f.write(json.dumps(dict(u, day=date.today().isoformat(), kind="menu",
                                    at=datetime.now(timezone.utc).isoformat(timespec="seconds"))) + "\n")


def _call(system, content, max_tokens, effort="low"):
    """One Sonnet call that must return a JSON object. Returns (obj, usage)."""
    # Generation calls take 30-90 s; the shared client has a 20 s timeout meant for /check.
    msg = checker._client_get().with_options(timeout=300.0, max_retries=1).messages.create(
        model=MODEL, max_tokens=max_tokens, system=system,
        output_config={"effort": effort},
        messages=[{"role": "user", "content": content}],
    )
    text = "".join(b.text for b in msg.content if b.type == "text")
    m = re.search(r"\{.*\}", text, re.S)
    if not m:
        raise RuntimeError(f"no JSON (stop={msg.stop_reason})")
    obj = json.loads(m.group(0))
    pin, pout = checker.PRICES.get(MODEL, (2.0, 10.0))
    usd = (msg.usage.input_tokens * pin + msg.usage.output_tokens * pout) / 1e6
    return obj, {"model": MODEL, "in": msg.usage.input_tokens, "out": msg.usage.output_tokens, "usd": round(usd, 6)}


# ---------- step 1: photos -> menu ----------
EXTRACT_SYSTEM = """You read photos of a restaurant or bar menu in Spain (usually Spanish, sometimes Valencian/Catalan or English) and write down exactly what is printed.

Rules:
- Only what is on the photos. Never add dishes, wines or prices that are not printed. If something is unreadable, skip it and mention it in "unreadable".
- Keep names as printed (fix only obvious OCR-like glitches). Keep the menu's own sections.
- Several photos may overlap; list each item once.
- Wines: fill type (tinto/blanco/rosado/espumoso/generoso/dulce), D.O. and grape only when printed or obvious from the name; else empty string.

Reply with only a JSON object:
{"name": "<restaurant name if printed, else empty>",
 "food": [{"section": "<menu section as printed>", "name": "", "desc": "<description as printed or empty>", "price": ""}],
 "wines": [{"name": "", "type": "", "do": "", "grape": "", "price": ""}],
 "drinks": [{"name": "", "kind": "cocktail|beer|spirit|soft|coffee|other", "desc": "", "price": ""}],
 "unreadable": "<short note in Russian, or empty>"}"""


def extract(code, images):
    _check_access(code)
    imgs = [i for i in images if isinstance(i, str) and len(i) > 100][:6]
    if not imgs:
        raise ValueError("no images")
    def media(i):  # "data:image/png;base64,...." -> image/png; the app sends JPEG
        m = re.match(r"data:(image/(?:jpeg|png|webp|gif));base64,", i)
        return m.group(1) if m else "image/jpeg"
    content = [{"type": "image", "source": {"type": "base64", "media_type": media(i),
                                            "data": i.split(",", 1)[-1]}} for i in imgs]
    content.append({"type": "text", "text": f"{len(imgs)} photo(s) of one menu. Transcribe it."})
    menu, usage = _call(EXTRACT_SYSTEM, content, 16000, effort="medium")
    _log([usage])
    for k in ("food", "wines", "drinks"):
        menu[k] = [x for x in menu.get(k) or [] if isinstance(x, dict) and str(x.get("name", "")).strip()]
    menu["cost"] = usage["usd"]
    return menu


# ---------- step 2: menu -> pack ----------
COMMON = """You write training material for a Russian-speaking waiter/bartender who has just been hired at THIS restaurant in Valencia, Spain, and must sound natural and confident with guests in Spanish (Spain register: tú/vosotros in casual places, usted in the alternative) and with tourists in English.

Hard rules:
- Use only dishes, wines and drinks from the menu given. Never invent items, prices or house specials.
- You do not know this kitchen's real recipe. For ingredients and allergens give what the dish TYPICALLY contains and always mark it as typical ("normalmente", "suele llevar") and add "confirmar con cocina" for allergens.
- Wine pairings: pick from THIS menu's wine list. If the list is empty, name a style ("un blanco fresco", "un tinto joven") instead of a brand.
- Spanish must be what a real waiter in Spain says, not a textbook calque. Short and speakable. Check gender and number agreement (los mejillones, las clóchinas, dos cañas).
- Russian fields are natural Russian, English fields natural English, Spanish fields Spanish from Spain.
Reply with only a JSON object, no other text."""

CARD_FIELDS = """Each card is an object with exactly these fields. Every field is in the language its name says: "ru" and "note" are in RUSSIAN (Cyrillic), "p_en"/"en"/"note_en" in English, "p_es"/"note_es" in Spanish.
"kind": "word",
"es": the item name exactly as on the menu, WITHOUT the printed description,
"ru": in Russian: what it is, without naming it (a guest-facing description to recall the name from),
"p_en": the same description in English, without the name,
"p_es": the same description in Spanish, without the name or its main word,
"en": the item name/short gloss in English,
"note": two selling adjectives in Spanish, then one Spanish sentence the waiter says to sell it in «», then (optional) a short tip in Russian,
"note_en": the same, with the tip in English,
"note_es": the same, with the tip in Spanish,
"extra": an object with short Spanish values: for dishes {"suele llevar": "...", "alérgenos": "... (confirmar con cocina)", "vino": "..."}; for wines {"estilo": "...", "va con": "<dishes from this menu>"}; for drinks {"lleva": "...", "vaso": "..."}

Example (for a dish "Croquetas de jamón" on a menu with a Verdejo):
{"kind": "word", "es": "Croquetas de jamón", "ru": "Обжаренные шарики из нежного бешамеля с хамоном, хрустящие снаружи", "p_en": "Fried balls of creamy béchamel with cured ham, crispy outside", "p_es": "Bolitas fritas de bechamel cremosa con jamón, crujientes por fuera", "en": "Ham croquettes", "note": "cremosas, caseras. «Son caseras, crujientes por fuera y muy cremosas por dentro.» Хороший старт, пока ждут рис.", "note_en": "cremosas, caseras. «Son caseras, crujientes por fuera y muy cremosas por dentro.» A good starter while they wait for the rice.", "note_es": "cremosas, caseras. «Son caseras, crujientes por fuera y muy cremosas por dentro.» Buen entrante mientras esperan el arroz.", "extra": {"suele llevar": "bechamel, jamón, pan rallado", "alérgenos": "gluten, leche, huevo (confirmar con cocina)", "vino": "Verdejo"}}"""


CYR = re.compile(r"[А-Яа-яЁё]")


def _cards_ok(items, n_expected):
    """The model sometimes writes "ru" in English; such a batch is regenerated."""
    if not isinstance(items, list) or len(items) < max(1, n_expected - 2):
        return False
    bad = sum(1 for c in items if not (isinstance(c, dict) and CYR.search(str(c.get("ru", "")))))
    return bad <= len(items) // 5


def _gen_cards(menu_name, kind, items, wines):
    wl = "; ".join(f"{w['name']} ({w.get('type','')})" for w in wines) or "(no wine list)"
    listing = "\n".join(f"- [{it.get('section','')}] {it['name']}" + (f" — {it['desc']}" if it.get('desc') else "") for it in items)
    text = (f"Restaurant: {menu_name or 'unknown'}\nWine list: {wl}\n\nWrite one card for each of these {kind}:\n{listing}\n\n"
            f"{CARD_FIELDS}\n\nReply: {{\"items\": [<one card per listed item, same order>]}}")
    obj, u = _call(COMMON, text, 16000)
    if not _cards_ok(obj.get("items"), len(items)):
        raise RuntimeError("cards: wrong count or Russian fields not in Russian")
    return obj.get("items") or [], u


def _gen_phrases_quiz(menu_text):
    text = f"""Menu:\n{menu_text}

1) Write 24 "phrases": things this waiter must SAY out loud with these exact dishes and drinks — recommending, describing, upselling, pairing a wine from this list, answering "what do you recommend", warning about allergens/waiting times, taking the order. Each phrase object:
"kind": "phrase", "ru": the situation in RUSSIAN, Cyrillic (what to do, not the answer), "p_en": the situation in English, "p_es": the situation in Spanish as an instruction to the waiter (without the answer), "es": the answer a native waiter says (max ~20 words; grammatical Spanish, e.g. "dos cañas de Turia", never brand names glued to plurals), "es_alt": a polite usted variant, "en": the same for an English-speaking tourist, "note": short Russian tip or empty, "note_en", "note_es": the tip in English/Spanish (empty if note is empty).

2) Write 15 "quiz" questions about THIS menu (what does dish X usually contain, which allergen to warn about, which wine from the list fits dish Y, which dish to suggest for a guest who wants Z). Each: "q": question in Spanish, "options": 3 strings, "answer": index of the right option (vary it), "why": Russian one-sentence explanation, "why_en", "why_es".

Reply: {{"phrases": [...], "quiz": [...]}}"""
    return _call(COMMON, text, 16000)


def _gen_scenes(menu_text):
    text = f"""Menu:\n{menu_text}

Write 2 branching role-play scenes at this restaurant where the waiter serves guests using these exact dishes and drinks: scene 1 in Spanish with local guests (ordering, a recommendation, a wine, a small problem such as an allergy or a dish that ran out, dessert/coffee, the bill); scene 2 in English with tourists who don't know Spanish food.
Each scene: {{"title": Russian, "title_en", "title_es", "lang": "es"|"en", "context": Russian one line, "context_en", "context_es", "start": "n1", "nodes": {{...}}}}.
Each node: {{"guest": the guest's line (in the scene language; may be omitted when the waiter speaks first), "hint": Russian short instruction for the waiter, "hint_en", "hint_es", "you": [1-2 reference answers in the scene language, max ~20 words], "next": [{{"label": short guest reaction in the scene language, "to": node id}}]}}.
End nodes: {{"guest": "...", "end": true}}. 10-14 nodes per scene, at least 2 branch points and 2 endings, every "to" must exist, every node reachable from "n1".
Reply: {{"scenes": [<2 scenes>]}}"""
    return _call(COMMON, text, 16000)


def _menu_text(menu):
    lines = [f"Restaurant: {menu.get('name') or 'unknown'}", "Food:"]
    lines += [f"- [{f.get('section','')}] {f['name']}" + (f" — {f['desc']}" if f.get('desc') else "") for f in menu.get("food", [])]
    lines.append("Wines:")
    lines += [f"- {w['name']} ({w.get('type','')} {w.get('do','')} {w.get('grape','')})".strip() for w in menu.get("wines", [])]
    lines.append("Other drinks:")
    lines += [f"- {d['name']} ({d.get('kind','')})" + (f" — {d['desc']}" if d.get('desc') else "") for d in menu.get("drinks", [])]
    return "\n".join(lines)


def _clean_card(c, pid, n, kind="word"):
    if not isinstance(c, dict) or not str(c.get("es", "")).strip():
        return None
    out = {"id": f"{pid}-{n:03d}", "kind": kind}
    for k in ("ru", "es", "es_alt", "en", "p_en", "p_es", "note", "note_en", "note_es"):
        v = c.get(k)
        if isinstance(v, str) and v.strip():
            out[k] = v.strip()
    if isinstance(c.get("extra"), dict):
        out["extra"] = {str(k): str(v) for k, v in c["extra"].items() if v}
    out.setdefault("ru", out.get("p_en") or out["es"])
    out.setdefault("p_en", out.get("en") or out["ru"])
    out.setdefault("p_es", out["ru"])
    return out


def _valid_scene(sc):
    nodes = sc.get("nodes") or {}
    if sc.get("start") not in nodes or sc.get("lang") not in ("es", "en"):
        return False
    for n in nodes.values():
        if not isinstance(n, dict):
            return False
        for x in n.get("next") or []:
            if x.get("to") not in nodes:
                return False
        if not n.get("end") and not n.get("next"):
            return False
    seen, stack = set(), [sc["start"]]
    while stack:
        k = stack.pop()
        if k in seen:
            continue
        seen.add(k)
        stack += [x["to"] for x in nodes[k].get("next") or []]
    return seen == set(nodes)


def _save(pid, pack):
    os.makedirs(PACKS, exist_ok=True)
    tmp = os.path.join(PACKS, pid + ".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(pack, f, ensure_ascii=False)
    os.replace(tmp, os.path.join(PACKS, pid + ".json"))


def load(pid):
    if not re.fullmatch(r"[a-z0-9]{10}", pid or ""):
        raise ValueError("bad id")
    with open(os.path.join(PACKS, pid + ".json"), encoding="utf-8") as f:
        return json.load(f)


def start_build(code, menu):
    _check_access(code)
    food = [f for f in (menu.get("food") or []) if isinstance(f, dict) and f.get("name")][:120]
    wines = [w for w in (menu.get("wines") or []) if isinstance(w, dict) and w.get("name")][:60]
    drinks = [d for d in (menu.get("drinks") or []) if isinstance(d, dict) and d.get("name")][:60]
    if not food and not wines and not drinks:
        raise ValueError("empty menu")
    menu = {"name": str(menu.get("name") or "")[:80], "food": food, "wines": wines, "drinks": drinks}
    pid = secrets.token_hex(5)
    _save(pid, {"id": pid, "status": "building", "name": menu["name"], "progress": "0", "menu": menu,
                "created": datetime.now(timezone.utc).isoformat(timespec="seconds")})
    threading.Thread(target=_build, args=(pid, menu), daemon=True).start()
    return {"id": pid}


def _build(pid, menu):
    name = menu["name"] or "Mi restaurante"
    mtext = _menu_text(menu)
    jobs = []   # (label, fn, args)
    for i in range(0, len(menu["food"]), CHUNK):
        jobs.append(("food", _gen_cards, (name, "dishes", menu["food"][i:i + CHUNK], menu["wines"])))
    bev = [dict(w, section="Vinos") for w in menu["wines"]] + [dict(d, section="Bebidas") for d in menu["drinks"]]
    for i in range(0, len(bev), CHUNK + 3):
        jobs.append(("drinks", _gen_cards, (name, "wines and drinks", bev[i:i + CHUNK + 3], menu["wines"])))
    jobs.append(("phrases", _gen_phrases_quiz, (mtext,)))
    jobs.append(("scenes", _gen_scenes, (mtext,)))

    results, usage, errors, done = {}, [], [], 0

    def run(job):
        label, fn, args = job
        for attempt in range(2):
            try:
                return label, args, fn(*args)
            except Exception as e:  # noqa: BLE001 - retry once, then report the part as missing
                err = repr(e)[:200]
        return label, args, err

    with ThreadPoolExecutor(max_workers=6) as ex:
        for label, args, res in ex.map(run, jobs):
            done += 1
            if isinstance(res, str):
                errors.append(f"{label}: {res}")
            else:
                obj, u = res
                usage.append(u)
                results.setdefault(label, []).append((args, obj))
            pack = load(pid)
            pack["progress"] = f"{done}/{len(jobs)}"
            _save(pid, pack)
    _log(usage)

    # assemble
    n = 0
    food_secs, drink_secs = {}, {}
    for label, secs in (("food", food_secs), ("drinks", drink_secs)):
        for args, items in results.get(label, []):
            src = args[2]
            for k, c in enumerate(items):
                n += 1
                card = _clean_card(c, pid, n)
                if not card:
                    continue
                sec_name = (src[k].get("section") if k < len(src) else "") or ("Carta" if label == "food" else "Bebidas")
                secs.setdefault(sec_name, []).append(card)
    sections = [{"id": f"s{i}", "title": t, "title_en": t, "title_es": t, "items": its}
                for i, (t, its) in enumerate(list(food_secs.items()) + list(drink_secs.items()))]
    phrases, quiz, scenes = [], [], []
    for _, obj in results.get("phrases", []):
        for c in obj.get("phrases") or []:
            n += 1
            card = _clean_card(c, pid, n, "phrase")
            if card:
                phrases.append(card)
        for q in obj.get("quiz") or []:
            opts = q.get("options") or []
            if isinstance(opts, list) and len(opts) >= 2 and isinstance(q.get("answer"), int) and 0 <= q["answer"] < len(opts):
                quiz.append({k: q[k] for k in ("q", "options", "answer", "why", "why_en", "why_es") if k in q})
    for _, obj in results.get("scenes", []):
        for i, sc in enumerate(obj.get("scenes") or []):
            if isinstance(sc, dict) and _valid_scene(sc):
                sc["id"] = f"{pid}-scene{i + 1}"
                scenes.append(sc)
            else:
                errors.append(f"scene {i + 1}: invalid graph, dropped")

    decks = []
    if sections:
        decks.append({"id": f"{pid}-carta", "title": f"Меню: {name}", "title_en": f"Menu: {name}",
                      "title_es": f"Carta: {name}", "sections": sections})
    if phrases:
        decks.append({"id": f"{pid}-frases", "title": f"Фразы: {name}", "title_en": f"Phrases: {name}",
                      "title_es": f"Frases: {name}", "sections": [{"id": "s0", "title": "Вслух в этом заведении",
                      "title_en": "Out loud at this place", "title_es": "En voz alta en este local", "items": phrases}]})
    pack = load(pid)
    pack.update({
        "status": "ready" if decks else "error", "progress": f"{len(jobs)}/{len(jobs)}",
        "decks": decks, "scenes": scenes,
        "quiz": {"id": f"{pid}-quiz", "title": f"Квиз: {name}", "title_en": f"Quiz: {name}", "title_es": f"Test: {name}",
                 "questions": quiz} if quiz else None,
        "errors": errors, "cost": round(sum(u["usd"] for u in usage), 4),
        "counts": {"cards": sum(len(s["items"]) for s in sections), "phrases": len(phrases), "quiz": len(quiz), "scenes": len(scenes)},
    })
    _save(pid, pack)
